In [1]:
import numpy as np
from dezero import Variable
import dezero.functions as F

In [12]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [13]:
x = Variable(np.random.randn(1,2,3))
y = x.reshape((2,3))
y

variable([[ 0.66906389  0.95561222 -0.09807935]
          [-2.29512007  0.73562562 -1.52176206]])

In [14]:
y = x.reshape(2,3)
y

variable([[ 0.66906389  0.95561222 -0.09807935]
          [-2.29512007  0.73562562 -1.52176206]])

In [3]:
x = Variable(np.random.rand(2,3))
y = x.transpose()
y = x.T
y

variable([[0.23468955 0.60336981]
          [0.00127617 0.25992116]
          [0.62461519 0.66042354]])

In [4]:
x

variable([[0.23468955 0.00127617 0.62461519]
          [0.60336981 0.25992116 0.66042354]])

In [5]:
A, B, C, D = 1, 2, 3, 4
x = np.random.rand(A, B, C, D)

In [6]:
x

array([[[[0.941645  , 0.0976962 , 0.61419846, 0.68484994],
         [0.36408866, 0.81738318, 0.01037773, 0.27374398],
         [0.17945959, 0.72713228, 0.87726777, 0.34802345]],

        [[0.03362671, 0.62695461, 0.05493014, 0.30846796],
         [0.45219095, 0.30165381, 0.70811253, 0.99389119],
         [0.97430049, 0.73963952, 0.62567881, 0.78378773]]]])

In [7]:
x.shape

(1, 2, 3, 4)